# Generated by Django 4.1.6 on 2023-02-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_name',
        ),
        migrations.AddField(
            model_name='lead',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
