# Generated by Django 4.1.6 on 2023-08-01 17:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_remove_lead_first_name_remove_lead_last_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("created_date", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "last_updated_date",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                ("converted_date", models.DateTimeField(blank=True, null=True)),
                ("tenant_map_id", models.IntegerField(default=1)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leads.agent",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leads.userprofile",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities",
                        to="leads.parties",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leads.leadsource",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        default="New",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leads.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("primary_number", models.CharField(max_length=30)),
                ("whatsapp_number", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                (
                    "preferred_contact_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leads.preferredcontact",
                    ),
                ),
                (
                    "user_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leads.usertype",
                    ),
                ),
            ],
        ),
    ]
