# Generated by Django 4.1.6 on 2023-08-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_alertoptions_calendardisplayoptions_repeatoptions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="owner",
            field=models.CharField(default="test@gmail.com", max_length=100),
            preserve_default=False,
        ),
    ]
