# Generated by Django 4.1.6 on 2023-08-04 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_opportunities_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, default='TODO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.taskstatusoptions'),
        ),
    ]
