# Generated by Django 3.1.4 on 2023-08-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20230812_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='kpi_lead',
        ),
    ]
