# Generated by Django 3.1.4 on 2023-08-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_targets_target_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='targets',
            name='target_points',
            field=models.IntegerField(default=1),
        ),
    ]
