# Generated by Django 3.1.4 on 2023-08-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_remove_kpi_kpi_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='condition2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
