# Generated by Django 3.1.4 on 2023-08-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20230813_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='condition2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
