# Generated by Django 3.1.4 on 2023-08-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20230820_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition1',
            name='module',
        ),
        migrations.AddField(
            model_name='module',
            name='fields',
            field=models.ManyToManyField(blank=True, to='leads.Condition1'),
        ),
    ]
