# Generated by Django 4.1.6 on 2023-08-01 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0005_task_organization"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TravelTimeOptions",
            new_name="TaskStatusOptions",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="travel_time",
            new_name="status",
        ),
        migrations.RemoveField(
            model_name="task",
            name="alert",
        ),
        migrations.RemoveField(
            model_name="task",
            name="all_day",
        ),
        migrations.RemoveField(
            model_name="task",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="task",
            name="location",
        ),
        migrations.RemoveField(
            model_name="task",
            name="referenceURL",
        ),
        migrations.RemoveField(
            model_name="task",
            name="repeat",
        ),
        migrations.RemoveField(
            model_name="task",
            name="showAs",
        ),
        migrations.RemoveField(
            model_name="task",
            name="start_time",
        ),
        migrations.AddField(
            model_name="task",
            name="designated_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="designatedLead",
                to="leads.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization",
                to="leads.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner",
                to="leads.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="referenceNotes",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name="AlertOptions",
        ),
        migrations.DeleteModel(
            name="CalendarDisplayOptions",
        ),
        migrations.DeleteModel(
            name="RepeatOptions",
        ),
    ]
