# Generated by Django 4.1.6 on 2023-08-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_rename_traveltimeoptions_taskstatusoptions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="invitees",
        ),
        migrations.AddField(
            model_name="task",
            name="invitees",
            field=models.ManyToManyField(to="leads.userprofile"),
        ),
    ]
