# Generated by Django 4.1.6 on 2023-08-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0007_remove_task_invitees_task_invitees"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
