# Generated by Django 3.1.4 on 2023-08-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_kpi_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordselectionrange',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
