# Generated by Django 4.1.6 on 2023-08-14 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_agent_id_alter_category_id_alter_condition1_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunities',
            name='original_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lead'),
        ),
    ]
