# Generated by Django 4.1.6 on 2023-08-14 13:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0009_condition1_condition2_conditionoperator_recipient_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepeatOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="taskattendees",
            old_name="attendee",
            new_name="participant",
        ),
        migrations.RemoveField(
            model_name="kpi",
            name="kpi_lead",
        ),
        migrations.RemoveField(
            model_name="task",
            name="designated_lead",
        ),
        migrations.AddField(
            model_name="kpi",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="leads.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="creation_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="task",
            name="designated_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="designatedAgent",
                to="leads.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="leads.lead",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reminder",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="condition2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="leads.category",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="invitees",
            field=models.ManyToManyField(blank=True, to="leads.userprofile"),
        ),
        migrations.CreateModel(
            name="Targets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "time_period",
                    models.CharField(
                        choices=[
                            ("Daily", "Daily"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Yearly", "Yearly"),
                        ],
                        max_length=100,
                    ),
                ),
                ("for_org", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "agents",
                    models.ManyToManyField(
                        blank=True, related_name="agents", to="leads.userprofile"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org",
                        to="leads.userprofile",
                    ),
                ),
                (
                    "related_kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="leads.kpi"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Opportunities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("created_date", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "last_updated_date",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                ("converted_date", models.DateTimeField(blank=True, null=True)),
                ("deal_amount", models.IntegerField(blank=True, null=True)),
                ("tenant_map_id", models.IntegerField(default=1)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leads.agent",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leads.userprofile",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities",
                        to="leads.parties",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leads.leadsource",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leads.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("primary_number", models.CharField(max_length=30)),
                ("whatsapp_number", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                (
                    "preferred_contact_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leads.preferredcontact",
                    ),
                ),
                (
                    "user_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leads.usertype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="repeat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="leads.repeatoptions",
            ),
        ),
    ]
