# Generated by Django 4.1.6 on 2023-08-14 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_task_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups_opp', to='leads.opportunities'),
        ),
    ]
