# Generated by Django 4.1.6 on 2023-08-14 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_followup_opportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.parties'),
        ),
    ]
